
title: DestinE DataLake Lab
author: Destination Earth Team
only_build_toc_files: true

repository:
  url: https://github.com/katharinastarzer21/DestinE
  branch: main
  path_to_book: ""



only_build_toc_files: true

html:
  use_repository_button: true

execute:
  execute_notebooks: "off"

# Lade zusätzliche Sphinx-Erweiterungen
sphinx:
  extra_extensions: []

# Aktiviere MyST Parser (für Markdown)
parse:
  myst_enable_extensions:
    - deflist
    - dollarmath
    - colon_fence
    - html_image