name: Add Repository to Gallery

on:
  issues:
    types: [opened, labeled]

jobs:
  process-request:
    if: contains(github.event.issue.labels.*.name, 'add-repo')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pip install pyyaml sphinx

    - name: Save Issue Body to File
      run: |
        echo "${{ github.event.issue.body }}" > issue_body.txt

    - name: Parse and Update YAML (external script)
      run: |
        python3 parse_issue.py

    - name: Clone new Cookbook Repository
      run: |
        git clone $REPO_URL cookbooks/$ROOT_PATH

    - name: Ensure README exists
      run: |
        if [ ! -f cookbooks/$ROOT_PATH/README.md ]; then
          echo "# Welcome to $ROOT_PATH" > cookbooks/$ROOT_PATH/README.md
        fi

    - name: Build HTML from Cookbook (with global conf.py and index.rst)
      run: |
        sphinx-build -b html cookbooks/$ROOT_PATH _build/html/$ROOT_PATH -c .

    - name: Commit updated YAML and Built HTML
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add notebook_gallery.yaml cookbooks/$ROOT_PATH _build/html/$ROOT_PATH
        git commit -m "Added new cookbook and built HTML"
        git push origin main
