name: Deploy Cookbook Gallery to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build central gallery (HTML mit cookbooks index etc.)
        run: |
          sphinx-build -b html . _temp_gallery

      - name: Copy built cookbooks into _site
        run: |
          mkdir -p _site
          cp -r _temp_gallery/* _site/
          cp -r cookbooks/* _site/

      - name: Disable Jekyll (allow folders like _static)
        run: touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
