name: Deploy Sphinx to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build HTML
        run: |
            sphinx-build -b html . docs -c .
        